### ISSUE TITLE
Limiter implementation

### ISSUE THREAD

**Issue by MrWaggel** [Lineblocs/internals-api#7]
Hey I saw you guys are using my [golimiter](https://github.com/MrWaggel/golimiter) package, but upon inspection I see the implementation has a small flaw.

https://github.com/Lineblocs/internals-api/blob/38363975c4105682baaf1f82c731fee86d0a810c/main.go#L112-L135

Every time `limitHandler(c echo.Context)` is called a new instance of `golimiter` will be created via `var indexLimiter = golimiter.New(limit, time.Minute)`.

This would mean that none of the previous increments for a given key will ever be found since it contains no keys. I suggest you move and instantiate the `var indexLimiter` outside the handler and reuse it.

**Comment by nadirhamid** [comment]
Hello @MrWaggel,

Thanks for the input, I will look into making these changes.
